// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5422.Minimec.commands.Arm;
import com.ctre.phoenix.motorcontrol.ControlMode;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5422.Minimec.Robot;
import org.usfirst.frc5422.Minimec.PixyObject.PixyType;
import org.usfirst.frc5422.Minimec.PixyObject;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc5422.Minimec.subsystems.PixyVision;

/**
 *
 */
public class ArmOverride extends Command {
    Joystick joy;

    public ArmOverride() {
        requires(Robot.arm);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        if (Robot.debug) System.out.println("ArmOverride initialize()");
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if(getArmJoystick() == 1) {
            Robot.arm.moveUpManual();
        }
        else if(getArmJoystick() == -1) {
            Robot.arm.moveDownManual();
        }
        else {
            Robot.arm.hold();
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        System.out.println("ArmOverride end()");
        Robot.arm.hold();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        System.out.println("ArmOverride interrupted()");
        Robot.arm.hold();
    }

    private double getArmJoystick()
    {
        return -1 * Robot.oi.getJoystick2().getRawAxis(1);
    }
}
