// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5422.Minimec.commands.Arm;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5422.Minimec.Robot;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc5422.Minimec.subsystems.PixyVision;

/**
 *
 */
public class ArmToPosition extends Command {
    int m_position;
    Boolean m_is_finished;

    public ArmToPosition(int position) {
        System.out.println("ArmToPosition() : " + m_position);
        m_position = position;
        if (Robot.useArm) requires(Robot.arm);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        System.out.println("ArmToPosition.initialize() : " + m_position);
        m_is_finished = false;
    }

    @Override
    protected void execute() {
        m_is_finished = Robot.arm.moveToPosition(m_position);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        // Return control to default command (ArmOverride)
        return (m_is_finished);
    }

    // Called once after isFinished returns true
    @Override

    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        System.out.println("ArmToPosition.interrupted() : " + m_position);
        Robot.arm.stop();
    }

}
