// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5422.Minimec.subsystems.pneumatics;


import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.Compressor;
import org.usfirst.frc5422.Minimec.commands.Pneumatics.RunCompressor;
import org.usfirst.frc5422.utils.StormProp;
import org.usfirst.frc5422.Minimec.Robot;


/**
 *
 */
public class Compression extends Subsystem {
    private boolean running;
    private Compressor mainCompressor;

    public Compression() {
        mainCompressor = new Compressor(StormProp.getInt("CompressorModuleId",-1));
        addChild("MainCompressor",mainCompressor);
        mainCompressor.setClosedLoopControl(false);
        running = false;
    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new RunCompressor());
    }

    @Override
    public void periodic() {

    }

    public boolean isActiveAndCharged() {
        return (running && mainCompressor.getPressureSwitchValue());
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void startCompressor() {
        running = true;
        mainCompressor.setClosedLoopControl(true);
        mainCompressor.start();

        if (Robot.debug) System.out.println("Compressor status: " + mainCompressor.enabled());
        if (Robot.debug) System.out.println("Compressor value: " + mainCompressor.getPressureSwitchValue());
        if (Robot.debug) System.out.println("Compressor current: " + mainCompressor.getCompressorCurrent());
    }

    public void stopCompressor(){
        mainCompressor.setClosedLoopControl(false);
        mainCompressor.stop();
        if (Robot.debug) System.out.println("Compressor off: " + !mainCompressor.enabled());
        running = false;
    }
}
