/*----------------------------------------------------------------------------*/
/* Copyright (c) 2018 FIRST. All Rights Reserved.                             */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package org.usfirst.frc5422.Minimec.subsystems;

import org.usfirst.frc5422.Minimec.Robot;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc5422.utils.StormProp;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;

/**
 *
 */
public class LidarAlign extends PIDSubsystem {

    private double m_pid_out;
    private NetworkTableEntry m_raw_entry;
    private NetworkTableEntry m_ena_entry;
    private boolean useShuffleboard = StormProp.getBoolean("debugconfig", false);

    // Leave setpoint at 0. We will calculate relative position to target
    // so that we can always set input to 0 when we don't have an object
    // to keep the PID from reacting.

    // Initialize your subsystem here
    public LidarAlign() {
        super("LidarAlign", 1, 0.00002, .1, 0.0, .01);
        getPIDController().setContinuous(false);
        getPIDController().setName("LidarAlign", "PIDSubsystem Controller");
        LiveWindow.add(getPIDController());
        getPIDController().setAbsoluteTolerance(5);   // FIXME property LidarPidTolerance
        getPIDController().setOutputRange(-0.2 , 0.2);  // FIXME property LidarPidRange

        if (useShuffleboard) {
        ShuffleboardTab debug_tab = Shuffleboard.getTab("LidarAlignDebug");
        m_raw_entry = debug_tab.add("Sensor Value (cm)", 0).getEntry();
        m_ena_entry = debug_tab.add("Enabled", false).getEntry();
        SmartDashboard.getNumber("Lidar PID Value", get_pid_output()); }
        //TODO: Test the line above
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }


    public void enable() {
        getPIDController().enable();
        if (useShuffleboard) {
        SmartDashboard.putString("Lidar Alignment Subsystem", "ENABLED");
        m_ena_entry.setBoolean(true); }
    }

    public void disable() {
        getPIDController().disable();

        if (useShuffleboard) {
        SmartDashboard.putString("Lidar Alignment Subsystem", "DISABLED");
        m_ena_entry.setBoolean(false); }
    }

    @Override
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
        double offset = Robot.stormNetSubsystem.getLidarOffset();

        if (useShuffleboard) {
        m_raw_entry.setDouble(offset);
        SmartDashboard.putNumber("Lidar Offset (cm)",offset); }

        if (Math.abs(offset) < 30) {
            return(-1 * offset);
        } else {
            return(0);
        }
    }

    public double get_pid_output() {
        return(m_pid_out);
    }

    @Override
    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
        m_pid_out = output;  
    }

}

